### ISSUE TITLE
Anasayfadaki mentors ve mentees alanında infinite scroll kaldırılmalı

### ISSUE THREAD

**Issue by selimdoyranli** [cagataycali/find-mentor#100]
Bu alanlar için hali hazırda mentors ve mentees olarak kendi sayfaları bulunuyor. Bu sayfalar içerisinde infinite scroll / pagination yapısı bulunduğundan dolayı anasayfadaki UX'i geliştirmeye yönelik anasayfadaki bu iki alanda infinite scroll / pagination yapısı kaldırılmalıdır.

**Her iki alanda da 8 kart limiti olarak verisi ve gösterimi sağlanmalıdır.**

**Comment by cagataycali** [comment]
Harika feedback, kesinlikle baklava gondermemiz lazim evine!
Cozuldu
