### ISSUE TITLE
peer sayfalarında profil badgelerini ve qr kodun profle card dışına çıkması

### ISSUE THREAD

**Issue by batin** [cagataycali/find-mentor#105]

**Comment by batin** [comment]
![image](https://user-images.githubusercontent.com/34899913/101983407-03192680-3c8c-11eb-99c0-de4bb4e038d3.png)

![image](https://user-images.githubusercontent.com/34899913/101983568-0234c480-3c8d-11eb-81b8-8f936b26debf.png)

**Comment by cagataycali** [comment]
cozuldu
