### ISSUE TITLE
Twitter URL's can have @ (at) sign

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#119]
The case: https://findmentor.network/peer/ahmet-bugra-cakici

The Twitter address is: https://twitter.com/@ahmetbcakici
Should be cleared as https://twitter.com/ahmetbcakici (without @ sign)

The data have to be cleared at the generation step.

**Comment by sevkioruc** [comment]
https://github.com/cagataycali/find-mentor/pull/191

@ işaretlerini bu şekilde kaldırdım

**Comment by cagataycali** [comment]
Ellerine saglik!
