### ISSUE TITLE
'Mentor ve Mentee' text

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#123]
Whole project coded in English, but the profile page has one Turkish text.

"Mentor ve Mentee" -> "Mentor & Mentee"

![image](https://user-images.githubusercontent.com/9213230/102001595-db19d980-3d04-11eb-8477-a86cb3c0f340.png)

**Comment by tansionline** [comment]
i can do it.

**Comment by tansionline** [comment]
Done but i send all of them.
