### ISSUE TITLE
Connect the GitHub pull requests & discord

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#134]
We're mostly active on discord. We can get the issues / pull requests notification @ discord

**Comment by tansionline** [comment]
i can do this

**Comment by hasantezcan** [comment]
test

**Comment by hasantezcan** [comment]
test 2

**Comment by hasantezcan** [comment]
test 3

**Comment by hasantezcan** [comment]
https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks :+1:
