### ISSUE TITLE
Missing variable name in json

### ISSUE THREAD

**Issue by Abtektas** [cagataycali/find-mentor#159]
In persons.json, datetime variable name is missing. After the register with google forms option, datetime value has filling now by automatically. 
![screenshot](https://user-images.githubusercontent.com/15087318/102136804-f7378b00-3e6a-11eb-8d3f-0fd116dff35a.jpg)

**Comment by cagataycali** [comment]
Oh, I see. I'll fix this problem as soon as possible!

**Comment by cagataycali** [comment]
I'm on this.

**Comment by cagataycali** [comment]
Can you please check the result, I think I fixed it. @Abtektas

**Comment by Abtektas** [comment]
Yes, it fixed now. Thank you so much
