### ISSUE TITLE
Kullanıcının profilinindeki linkleri düzenlemesi.

### ISSUE THREAD

**Issue by AbdullahAki** [cagataycali/find-mentor#169]
Kullanıcı ilerleyen aşamalarda yeni bir platform eklemek isterse veya platformların linkini değiştirmek isterse bunu yapabilmesi için bir panel sunulabilir.

**Comment by cagataycali** [comment]
GitHub profil readme'si olusturarak diledigi gibi sayfasini sekillendirebilir

**Comment by selimdoyranli** [comment]
> GitHub profil readme'si olusturarak diledigi gibi sayfasini sekillendirebilir

Kurguyu yeniden değerlendirmemiz gerektiğini düşünüyorum. Kullanıcı sosyal medya hesaplarını değiştiremeyecekse bir hesabı atıl duruma düştüğünde sosyal medya hesabını göstermek anlamsız oluyor. Sadece README üzerinden referanslayacak isek sosyal medya alanına ihtiyacımız olmayabilir. Kullanıcılara README oluşturmaları ve bizim bunu okuyacağımıza dair yönerge verebiliriz. Kısa vadeli bir yaklaşım ise yani yakın bir zamanda güncelleme getirebilir isek şimdilik alanlar kalabilir.

**Comment by cagataycali** [comment]
Haklısın, kayıt alt yapısı excel üzerinden beslendiği için yeni bir soru eklemek sorunu çözer (yeni bir sosyal medya hesabı ekleme durumunda) ancak düzenleme için kişileri auth etme işini google forms'a bırakmıştık. Kişi gönderdiği yanıtı tekrar güncelleyebilyor bu sayede 
![image](https://user-images.githubusercontent.com/9213230/102252852-a762cd80-3f17-11eb-92e5-9808e39eb052.png)

Ancak daha sağlıklı bir çözüm için kendi kayıt alt yapımıza geçebiliriz, ilerleyen dönem işleri olarak düşünebiliriz bunu

**Comment by ahmetcanaydemir** [comment]
Github ile authorize mantıklı olabilir. Github ile giriş yapıldıysa ekleme veya zaten eklenmişse düzenleme sayfalarına erişim izni verilebilir.

**Comment by cagataycali** [comment]
Evet ben de benzer bir dusuncedeyim, github ile giris yaptirip bu satirlari duzenleme yetkisi verecegiz ileride

**Comment by cagataycali** [comment]
Ileride degerlendirmek uzere simdilik kapatiyorum
