### ISSUE TITLE
Anlık mentee mentor sayısını gösteren sayaç 

### ISSUE THREAD

**Issue by hasantezcan** [cagataycali/find-mentor#174]
Anlık mentee ve mentor sayılarını göstermeliyiz

**Comment by muraterzioglu** [comment]
@cagataycali abi json.parse ettikten sonra `length` ile birlikte yapmak mümkün olabilir mi?

**Comment by cagataycali** [comment]
Evet mümkün, generate.js incelenebilir

**Comment by cagataycali** [comment]
İnceliyoruz @hasantezcan ile beraber
