### ISSUE TITLE
Randomization of listing peers

### ISSUE THREAD

**Issue by ahmetcanaydemir** [cagataycali/find-mentor#185]
We need to randomize the lists every refresh or every build. It could be good for not showing same people with same order every time.

**Comment by cagataycali** [comment]
We can get the list by reverse order. registered_at column can be used as well.

**Comment by ahmetcanaydemir** [comment]
> We can get the list by reverse order. registered_at column can be used as well.

Actually I thought we can simply shuffle array using [Fisher–Yates algorithm](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) so every mentor and mentee could have a chance to shown in homepage or in first results of lists.


This is the sample implementation:
```js
function shuffle(a) {
    for (let i = a.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
}
```

Usage:
```js
shuffle(peerArray);
```

**Comment by cagataycali** [comment]
Can we add this feature in brand new page? Called 'Shuffle' ?

**Comment by ahmetcanaydemir** [comment]
May be. But not sure for need of new page for this.
