### ISSUE TITLE
Github Botumuz Şuan Çalışmıyor

### ISSUE THREAD

**Issue by tansionline** [cagataycali/find-mentor#199]
- Githubdaki  botumuz şuan excel içindeki dataları sitemize taşımıyor. 
Örnek:  
[2 gün önce](https://github.com/cagataycali/find-mentor/commit/fb88bb0393c072ff3a1af117729668c77d13d856)
[Şuan](https://github.com/cagataycali/find-mentor/commit/016aa763a15e854cfca84b03c81abc427e330d9e)

**Comment by cagataycali** [comment]
Inceliyorum

**Comment by cagataycali** [comment]
Cozuldu
