### ISSUE TITLE
Give feedback alanı sayfa yenilenince gözükmüyor

### ISSUE THREAD

**Issue by sevkioruc** [cagataycali/find-mentor#201]
Profil sayfasını yenilediğim zaman Give Feedback alanı gözükmüyor

![Ekran görüntüsü 2020-12-19 013132](https://user-images.githubusercontent.com/33834689/102667256-033c8900-419a-11eb-8e0d-8a2c5947a86a.png)

**Comment by ahmetcanaydemir** [comment]
@sevkioruc adblocker eklenti açık olduğunda mı yaşıyorsun?

**Comment by sevkioruc** [comment]
Hayır eklenti açık değil. Sende bu durum olmadı mı acaba ?

**Comment by ahmetcanaydemir** [comment]
> Hayır eklenti açık değil. Sende bu durum olmadı mı acaba ?

Sadece ublock açık olduğunda yaşıyorum

**Comment by selimdoyranli** [comment]
İlgili sorunun farkındayız. SSR ile birlikte 3. parti disqus embed.js dosyasının sayfaya bağlanırken oluşan kararsızlık bu hataya sebebiyet veriyor. Düzeltmek için üzerinde çalışıyoruz.
