### ISSUE TITLE
Discord linkinin sabit olması

### ISSUE THREAD

**Issue by AbdullahAki** [cagataycali/find-mentor#205]
Discord linkini findmentor.network/discord şeklinde yapabilirsiniz.

**Comment by muraterzioglu** [comment]
İlgileniyorum

**Comment by cagataycali** [comment]
Su an discord'u web sayfasinda aciyor. Deeplink varsa onda acmasi gerekiyordu. Bununla ilgilenip tekrar pr acabilir misin @muraterzioglu

Simdilik geri aliyorum kodu

**Comment by muraterzioglu** [comment]
> Su an discord'u web sayfasinda aciyor. Deeplink varsa onda acmasi gerekiyordu. Bununla ilgilenip tekrar pr acabilir misin @muraterzioglu
> 
> Simdilik geri aliyorum kodu

Yarın öğlene doğru halledip yolluyorum

**Comment by cagataycali** [comment]
https://github.com/cagataycali/find-mentor/pull/216/files#diff-e0bbdb799008f2d16aeba439bb35c88426c94af1392ba7c862a23177a186259dL51

Yukaridaki kodu geri alip adresi su ile degistirebiliriz: 

https://discord.gg/EDwkj6Z7W2

Bu link bozulmayacak

**Comment by cagataycali** [comment]
Cozuldu
