### ISSUE TITLE
GitHub avatar cache problemi

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#21]
GitHub'dan profillerin img'larini surekli isterken query string gonderiyoruz `?size`
Bu sebeple GH cache yapmiyor. Bu sureci optimize etmek adina bir cozum bulmaliyiz

**Comment by sevkioruc** [comment]
https://avatars.githubusercontent.com/${username} şeklinde query string kullanmadan avatarı aldıktan sonra css ile boyutunu ayarlarsak nasıl bir çözüm olur ?

**Comment by cagataycali** [comment]
harika cozum olur!
