### ISSUE TITLE
/peer route'u github username'leri ile calismali

### ISSUE THREAD

**Issue by mbugrayildiz** [cagataycali/find-mentor#211]
Generate ettigimiz json dosyalarinda degisiklige gitmemiz gerekebilir. #186 da belirtildigi gibi birkac mantikli optimizasyon icin persons.json'da olusturdugumuz custom slug'lar yerine github username'leri kullanabiliriz.

Bu sayede generate.js uzerinden yuk alip ayni zamanda data'mizi kucultmus oluruz.

__Bunun iyi bir fikir olduguna dair kanitlar:__

- github username'ler unique oldugu icin cakisma olasiligi 0
- zaten unique bir identifier varken neden iki tane tutalim?
- activeMentorships.json'da contributors diye biseye gerek kalmaz, frontend'de github'a request atariz.
    * zaten async olarak alip render vuracagimiz icin performans degismeyecek.
    * activeMentorships.json tek katmanli bir array olacak, duplicate data icinde bulunmayacak.
- #186 yi kafaya taktim illa cozecem

__Kotu yanlari:__

- kullanici github username'ini degistirirse adres bosa cikiyor.
- GitHub'i zorunlu hale getiriyoruz
    * ote yandan, bir yazilimcinin github'inin olmasi olmamasindan daha iyi
    * \+ google forms'da zaten field zorunlu

TL;DR
custom person slug'lar calismiyor, github username'leri ile degistirelim.

**Comment by mbugrayildiz** [comment]
@muraterzioglu @selimdoyranli @cagataycali @tansionline ne dusunuyorsunuz hocalarim?

**Comment by selimdoyranli** [comment]
Github ile kısıtlamaktan ziyade #169 #207 taleplerinde bahsettiğimiz custom authentication (github veya local) yapısına geçersek bu gibi case'leri de artık çok fazla düşünmek zorunda kalmıyoruz. Örneğin bir custom auth. yapısında site içerisinde oluşabilecek kullanıcı taraflı eksikliklerin bir çoğu artık sistemden ziyade kullanıcı tarafına atanmış olacak. Bunun sebebi google'daki gibi ucu açık bir form yerine kullanıcıya kendi standartımızda bir form sunmak. Kullanıcı bu formda örneğin sosyal medya verisini girer veya girmez. Aynı şekilde bu yapı ile birlikte /:username rotası yapısı da kolayca kurulabilir.

Öte yandan bunun bir dezavantajı; Şu anda sistemde her şey github profili üzerinden ilerliyor. Custom auth. olsa bile kullanıcıya bir form sunmadığımız takdirde projeleri, katkıları, readme gibi verileri yine uzaktan yani githubdan alacağımızı varsayarsak çift yapıda bir kod karmaşası yaratacaktır.

Detaylar değerlendirilebilir.

**Comment by muraterzioglu** [comment]
Auth sistemi ile çok fazla şey yapabiliriz ama o zaman altyapıda köklü değişikliklere gitmemiz gerekebilir kolaylık sağlaması açısından firebase auth sistemi kullanabilir hali hazırda bir sürü giriş sistemi zaten mevcut durumda.

>Öte yandan bunun bir dezavantajı; Şu anda sistemde her şey github profili üzerinden ilerliyor. Custom auth. olsa bile kullanıcıya bir form sunmadığımız takdirde projeleri, katkıları, readme gibi verileri yine uzaktan yani githubdan alacağımızı varsayarsak çift yapıda bir kod karmaşası yaratacaktır.
>

@nuxt/fire kullanarakta peer sayfalarını firestore ile build edebiliriz bence free paketi daily olarak işimizi görücektir diye düşünüyorum projeler ise array olarak , proje datalarını firestore üzerinde tutabiliriz. Aman aman bir masraf çıkartırmı bilmiyorum paket izinleri ile bizim daily data'ları karşılaştırmak lazım

veya projelerin sayfalarını gene json'da tutmakla beraber slug yapısı ile ilişki kurabiliriz

**Comment by cagataycali** [comment]
Firebase'e geçiş tamamlandıktan sonra buna göre devam edeceğiz ❤️
