### ISSUE TITLE
Fikir: Discord #jobs kanalı bot ile iş ilanı crawl edilmesi

### ISSUE THREAD

**Issue by muratdemirci** [cagataycali/find-mentor#212]
Bunu iki şekilde yapabiliriz yurtiçi/yurtdışı olarak:

- Yurtdışı için örnek url: https://ca.indeed.com/Software-Developer-jobs
indeed'in apisi : https://opensource.indeedeng.io/api-documentation/
-Yurtiçi için linkedini kullanabiliriz:
https://developer.linkedin.com/docs/guide/v2/jobs/recommended-jobs#linkedin-job-url 
https://api.linkedin.com/v2/recommendedJobs?q=byMember

Şuan için sadece bir fikir tabi ama covid19 nedeniyle çok fazla iş arayan dev ve şirket var.İş ilanlarını akış gibi stream edersek güzel olabilir.Artı olarak bunu efektif kullanabilirsek insanlara https://findmentor.network/ üzerinden iş ilanı postlamaları için basit bir form da verebiliriz.
Yine discord bot sayesinde #jobs section ı altına düşebilir.

**Comment by muraterzioglu** [comment]
Hiç botlara girişmeden webhook'larla yapabilceğimizi düşünüyorum formu post etmesi yeterli webhook'a @cagataycali abi sen ne dersin?

**Comment by muratdemirci** [comment]
> Hiç botlara girişmeden webhook'larla yapabilceğimizi düşünüyorum formu post etmesi yeterli webhook'a @cagataycali abi sen ne dersin?

Spesifik iş araması özelliği de ekleyebiliriz o yüzden bota biraz sıcak bakıyorum, mesela:
!{ulkeKodu} - {arananPozisyon}  !ca-software-developer

gibi.

**Comment by muraterzioglu** [comment]
Bunu bot'a issue olarak açsan süper olur https://github.com/muraterzioglu/find-mentor-dcbot

**Comment by muratdemirci** [comment]
> Bunu bot'a issue olarak açsan süper olur abi https://github.com/muraterzioglu/find-mentor-dcbot

Tamamdır, bu repoyu unutmusum.Bu issue yu komple bota taşıyayım o zaman.

**Comment by muraterzioglu** [comment]
Tamamdır 👍

**Comment by cagataycali** [comment]
İş ilanlarını direkt dışarıdan alsak?

**Comment by muratdemirci** [comment]
Olabilir, ben bir de ufak bir rep sistemi düşünüyorum burası için.Çok sıkıntılı şirketler olabiliyor (mobbing vs).
Dev'ler gizli oy ile şirketlere || ilanlara rep +/-  versinler.
Rep'i eksiye düşen şirketlerin ilanlarını yayınlamayalım kendi içimizde.Böylece insanların çalışırken mutlu olabileceği şirketleri bulmuş oluruz :)

**Comment by cagataycali** [comment]
Bak bu harika bir fikir, iceride direkt bu ozelligi kodlayalim ya da su projeyi yesillendirebiliriz https://github.com/cagataycali/entrylevel

**Comment by muratdemirci** [comment]
Şöyle de yapılabilir, ilk bu özelilği discorda eklersek ve iş ilanlarını da websitemiz üzerinden alırsak...Hem websitemiz hem de discord communitymiz gelişmiş olur.Buradan edindiğimiz tecrübeyle de entrylevel'ı yaparız sonra.Discorddaki #jobs kanalı hafiften hareketlenmeye başladı çünkü.

**Comment by cagataycali** [comment]
Katılıyorum, topluluk içinde bırakalım yan bir projeyi büyütmeyelim.

**Comment by cagataycali** [comment]
İş ilanlarını listeleyebileceğimiz bir sayfa oluşturdum, google forms üzerinden iş ilanlarını topluyor. Arayüzünü iyileştirmemiz gerekiyor ayrı bir iş olarak açacağım
