### ISSUE TITLE
New year theme

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#214]
We need a fancy touch for the new year!

**Comment by mbugrayildiz** [comment]
Shall we add a snowflake animation to bg?

**Comment by syspentarc** [comment]
In the new year generally, there are lots of colors around. Wouldn't it be more appropriate to add more color, not suggesting doing something big or anything like that... Maybe changing navbar colors inspired by fireworks or something else that resembles the new year.

**Comment by muratdemirci** [comment]
Changing the color palettes is a great idea @syspentarc ! We can use HEX color schemes like this 👍 

[<img src="https://i.pinimg.com/originals/c0/3d/ee/c03dee46025caa2c0ecd5082259485a1.jpg">](https://i.pinimg.com/originals/c0/3d/ee/c03dee46025caa2c0ecd5082259485a1.jpg)

**Comment by syspentarc** [comment]
Maybe changing some icons to match the theme. But I'm not sure what kinds of icons would be best-suited for that...

**Comment by cagataycali** [comment]
We didn't do that.
