### ISSUE TITLE
Activity Area

### ISSUE THREAD

**Issue by sevkioruc** [cagataycali/find-mentor#215]
We can add activity area for upcoming events. 

e.g. https://superpeer.com/cagatay/event/orhan-ozalp-ile-teknik-mulakatlar-hakkinda-soru-cevap

**Comment by cagataycali** [comment]
Related: https://github.com/cagataycali/find-mentor/issues/162

**Comment by cagataycali** [comment]
We can add an eventing system inside the community. I totally support this feature.

**Comment by hasantezcan** [comment]
I am working on it
