### ISSUE TITLE
Add social media links

### ISSUE THREAD

**Issue by hasantezcan** [cagataycali/find-mentor#218]
We should add these addresses on the site

Twitter: https://twitter.com/findmentorapp
YouTube: https://www.youtube.com/channel/UCx7Q-6Qqrf9TU5gY-i9xovA
Linkedin: https://www.linkedin.com/company/find-mentor-network

**Comment by tansionline** [comment]
[Merged](https://github.com/cagataycali/find-mentor/pull/229)
