### ISSUE TITLE
Can we create a interns page ? 

### ISSUE THREAD

**Issue by tansionline** [cagataycali/find-mentor#221]
Hi, I saw in discord an idea from  @muratdemirci. 

- We create a basic table like ```event page```.
- We create a new Google Form for business. 

Original Message: 
``` findmentor.network => staj arayan mentee ler için bir sayfa, findmentor.network/interns
çok fazla staj arayan ve iş hayatına güzel bir şirkette başlangıç yapmak isteyen arkadaşlar var.bunları listelememiz iyi olabilir.profilleri zaten bizde mevcut. bu fikir bir kenarda dursun. ```

**Comment by tansionline** [comment]
BTW, I gonna create this night interns page.

**Comment by muratdemirci** [comment]
There is little question mark in here,  should we use google forms again or should we make a little crud for that? 🤔Hımmm🤔

**Comment by tansionline** [comment]
Noted and i gonna think about it.

**Comment by cagataycali** [comment]
I created a form for this, and connect the actual code base. The feature is ready for developing UI <3
