### ISSUE TITLE
Hire me button should be clickable

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#235]
https://findmentor.network/peer/alper-babadag

As an example, 
![image](https://user-images.githubusercontent.com/9213230/103242030-f6702000-4965-11eb-9f8c-5925d72eb29d.png)

The hire me button should be clickable.

The candidate's mail exists in page memory.

**Comment by muratdemirci** [comment]
![Screenshot from 2020-12-29 22-13-27](https://user-images.githubusercontent.com/6681137/103308782-56c59700-4a24-11eb-8f35-10c572af4fdf.png)

Fixed! :)

**Comment by cagataycali** [comment]
Resolved by @muratdemirci.
