### ISSUE TITLE
Header Content Doesn't Fit on Smaller Screens

### ISSUE THREAD

**Issue by makiftutuncu** [cagataycali/find-mentor#249]
I'm using an old 13" MacBook Pro to view https://findmentor.network. The header content does not fit. It might be a good idea to use smaller fonts and icons or increase the threshold where items are folded into a menu.

Here are examples:

Full screen window (2560 px width)
<img width="1280" alt="Screen Shot 2021-01-02 at 15 06 53" src="https://user-images.githubusercontent.com/1009191/103456986-58d17380-4d0c-11eb-92b3-2a0310755543.png">

Slightly smaller window (1920 px width)
<img width="1072" alt="Screen Shot 2021-01-02 at 15 09 11" src="https://user-images.githubusercontent.com/1009191/103457033-c2ea1880-4d0c-11eb-91e4-258989e4be64.png">

**Comment by cagataycali** [comment]
Aww, we have to fix this. Thanks for your report, can you handle this bug, or we can help to fix that with you?

**Comment by makiftutuncu** [comment]
I don't know much about frontend but I could give it a shot. 😊

**Comment by makiftutuncu** [comment]
Just opened #250. We can discuss it further there, if needed. Thanks!

**Comment by hasantezcan** [comment]
Same issue in pivot screen

![image](https://user-images.githubusercontent.com/32804505/103460759-fbe4b600-4d29-11eb-8c3d-610346628c3f.png)

**Comment by cagataycali** [comment]
Resolved by @makiftutuncu! Thanks for your great support!
