### ISSUE TITLE
Profillere Twitter Embed

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#32]
Mentor ve mentee profillerine twitter embed'i koyarak profili daha rahat incelenebilir hale getirebiliriz

**Comment by cagataycali** [comment]
Ornegin kisinin readme.md dosyasini direkt markdown olarak alip iceriye markdown olarak koyabiliriz:

https://raw.githubusercontent.com/xcaq/xcaq/master/README.md

**Comment by Adem68** [comment]
#36
