### ISSUE TITLE
Add mentor emails

### ISSUE THREAD

**Issue by cemolcay** [cagataycali/find-mentor#38]
Mentor'lerin twitter, github ve linkedin dışında insanların direkt ulaşabilmesi adına email'lerinin de yer alması güzel olabilir sanki?

**Comment by cagataycali** [comment]
Evet harika olurdu, ancak datayı geriye dönük tamamlamak zor olduğu için GitHub readme'leri eklemeyi düşündük;
Örnek şu şekilde oldu: https://findmentor.network/mentor/saffet-bulut/

**Comment by fatih-yavuz** [comment]
> Evet harika olurdu, ancak datayı geriye dönük tamamlamak zor olduğu için GitHub readme'leri eklemeyi düşündük;
> Örnek şu şekilde oldu: https://findmentor.network/mentor/saffet-bulut/

harika olmus 🚀

**Comment by cagataycali** [comment]
Cozumlendigini dusunuyorum
