### ISSUE TITLE
Display current company

### ISSUE THREAD

**Issue by fatih-yavuz** [cagataycali/find-mentor#39]
Kisilerin sirketleri, profil kartlarinin altinda gosterilmesi icin bir gelistirme yapabilirim.

Bu bilgiyi LinkedIn profillerinden alabiliriz. 

Ek olarak, en cok endorse almis top 3 yeteneklerini de gosterebiliriz.

**Comment by cagataycali** [comment]
Ef-sa-ne olur!

**Comment by fatih-yavuz** [comment]
linkedin profillerini scrape etmek API token kullanmadan + cok buyuk efor sarfetmeden imkansiz. Login olmayan kullanicilar icin bile DNS seviyesinde worker calistirip cookie kontrolu yapiyorlar.
