### ISSUE TITLE
URL Düzeltme

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#4]
Kişilerin excel'e girdiği GitHub, LinkedIn, Twitter adreslerinde eksikler mevcut. `http` ile başlamayan linklerin başına http koymamız gerekiyor. Aksi halde `findmentor.network/github.com` şeklinde url'ler oluşur

**Comment by tansionline** [comment]
Yardim ediyorum.

**Comment by cagataycali** [comment]
Excel'deki data her zaman bozuk gelecek, insan tarafindan giriliyor kimseyi http ile yaz diye zorlayamayiz.
Kod tarafinda bunu kapsamaliyiz,

https://github.com/cagataycali/find-mentor/blob/master/pages/mentee/_slug.vue#L10

Yukarıda verdiğim adreste şuna benzer bir çözümle bunu yapabiliriz.

Kod şuna benzeyebilir; 

```javascript
<li v-if="doc.github && doc.github.length">
       <a :href="doc.github.startsWith('http') ? doc.github : `http://${doc.github}`">Github</a>
</li>
```

**Comment by tansionline** [comment]
Got it!

**Comment by cagataycali** [comment]
Bu isin dogru sekilde yapilma yontemi ise bir computed method uretip onu kullanmak,

https://vuejs.org/v2/guide/computed.html

isValidURL adinda bir metod olusturup tum linkleri ondan gecirmek gerekiyor

**Comment by cagataycali** [comment]
https://github.com/cagataycali/find-mentor/pull/7

**Comment by cagataycali** [comment]
@sevkioruc tarafindan cozuldu
