### ISSUE TITLE
Create a discord channel to communicate members

### ISSUE THREAD

**Issue by hasantezcan** [cagataycali/find-mentor#48]
I think we need a discord channel to communicate with each other. Thereby mentors meet with mentees in channels and making peer coding, discuss some topic stuff like that. 
I am starting to build it right now. :fireworks:

**Comment by cagataycali** [comment]
WOW!
THAT IS THE REAL GAME CHANGER!
LET'S BUILD THIS NOW PIVIIIIIIZ!

**Comment by hasantezcan** [comment]
https://github.com/cagataycali/find-mentor/pull/50 :rocket:
