### ISSUE TITLE
Mentees ve Mentors sayfalarında gelişmiş arama

### ISSUE THREAD

**Issue by selimdoyranli** [cagataycali/find-mentor#54]
- Arama sonuç listesi infinite scroll ile sürdürülebilir olmalı
- Case sensitive arama sağlanmalı
- Arama işlemleri tüm json yerine limite bağlanabilir
- <s>Arama anahtar kelimesi isim ve interest gibi çoklu alanlara bakabilir</s> ✅

**Comment by cagataycali** [comment]
Arama islemleri limite baglandiginda diger kisiler arasinda arama yapmayacagi icin dogru sonucu alamayiz diye dusunuyorum

**Comment by selimdoyranli** [comment]
Kurgu şöyle olmalı: 

'Ali' keyword'ünü girdiğimde Ali ile ilgili limit kadar kayıt getirmeli. Ne zaman infinite scrollu başlatırsam bir önceki sonucu skip edip var olan dizi sonucuna limit kadar push etmeli diye düşündüm.

Bu kurgu aslında 1. madde ile aynı yapıda gibi. Hem fikir isek 3. maddeyi silebilirim. Onaylıyor musun?

**Comment by cagataycali** [comment]
Simdi daha iyi anladim, kesinlikle katiliyorum. 3. maddeyi yanlis yorumlamisim, aciklama oldugu icin kalabilir diye dusunuyorum

**Comment by cagataycali** [comment]
Ilgi alanlari arama @ahmetelgun tarafindan https://github.com/cagataycali/find-mentor/pull/61 PR'inda yapildi
