### ISSUE TITLE
Responsive İyileştirmesi

### ISSUE THREAD

**Issue by selimdoyranli** [cagataycali/find-mentor#66]
Tablet ve Mobile Yönelik Arayüz bileşenlerinin görünümü projede sağlanan bootstrap referans alınarak iyileştirilmeli ve uyumlu hale getirilmeli.

**Comment by cagataycali** [comment]
Kesinlikle katılıyorum, mobilde gezinim çok hoş değil, 
* sayfanın dışına çıkabiliyor.
* Navigasyon da sağlıklı değil, gizlenip açılabilmeli ancak register butonu her zaman görünür olmalı

**Comment by cagataycali** [comment]
cozuldu
