### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by cagataycali** [cagataycali/find-mentor#73]
Her farklı editör/ide'de kodu gereğinden fazla farklı şekilde formatlayıp gönderiyoruz, standart olması amacıyla prettier koyalım

**Comment by hasantezcan** [comment]
https://github.com/cagataycali/find-mentor/pull/80

**Comment by cagataycali** [comment]
CI-CD surecine eslint ve prettier koymak gerekiyor. Her pull'da temiz kod almaliyiz
