### ISSUE TITLE
medium linki alanının eklenmesi

### ISSUE THREAD

**Issue by mstrYoda** [cagataycali/find-mentor#81]
linkedin github ve twitter linkleri bulunuyor, bunlara ek olarak medium linki eklenebilir

**Comment by cagataycali** [comment]
Datayi geriye donuk olarak almak cok guc oldugu icin kisilerin github readme'sini profillerinde gosterme ozelligi gelistirdik
Bu sayede sadece medium degil diger global sitelerin linklerini de paylasabiliyorlar, dribbble vs gibi

**Comment by cagataycali** [comment]
<3
