### ISSUE TITLE
Person Type Badge On Person Page

### ISSUE THREAD

**Issue by selimdoyranli** [cagataycali/find-mentor#99]
Kişi detay sayfasında ilgili kişinin mentor mu mentee mi yoksa her ikisi de mi olduğuna dair bir bilgilendirme mevcut değil. Arayüze yönelik çalışma olarak bilgilendirme ibarelerinin eklenmesi (badges, color vb.) gerekmektedir.

**Comment by selimdoyranli** [comment]
Tarafımdan çalışmaya alınmıştır.

**Comment by cagataycali** [comment]
Kesinlikle haklisin!
Harika olur bunu duzeltirsek
